name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        php-version: ['7.2', '7.3', '7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@1.4.6
      with:
        php-version: ${{ matrix.php-versions }}
    - name: PHP version
      run: php -v
    - name: Composer version
      run: composer -V
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run check
      run: composer check
